all: exercice1 client serveur

exercice1: exercice1.c 
	gcc -o exo1 exercice1.c -Wall

client: exercice2_2.c
	gcc -o client exercice2_2.c -Wall

serveur: exercice2_1.c
	gcc -o serveur exercice2_1.c -Wall

clean:
	rm client serveur exo1
